FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Create directory for uploaded files
RUN mkdir -p mpp_files

# We'll mount the code as a volume, so no need to copy it here
# Run Django's development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]