version: '3.8'

services:
  backend:
    image: ghcr.io/t-veera/mini-plm-backend:latest
    volumes:
      - ./mpp_files:/app/mpp_files
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.16
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mini_plm
    depends_on:
      - db
    restart: unless-stopped
    command: >
      bash -c "mkdir -p /app/mpp_files/uploads &&
               chmod -R 755 /app/mpp_files &&
               chown -R $(whoami):$(whoami) /app/mpp_files &&
               gunicorn --bind 0.0.0.0:8000 mpp_backend.wsgi:application"

  frontend:
    image: nginx:alpine  # serving static files with Nginx
    volumes:
      - ./mpp_frontend/build:/usr/share/nginx/html:ro
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./mpp_frontend/build:/var/www/frontend:ro
      - static_volume:/var/www/static
      - ./mpp_files:/var/www/media:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mini_plm
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
