services:
  backend:
    image: ghcr.io/t-veera/mini-plm-backend:latest
    volumes:
      - ./mpp_files:/app/mpp_files
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.16
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mini_plm
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    image: ghcr.io/t-veera/mini-plm-frontend:latest
    volumes:
      - build_volume:/app/build
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      # Mount the global nginx configuration to its proper location
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the site-specific configuration separately
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - build_volume:/var/www/frontend
      - static_volume:/var/www/static
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mini_plm
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  build_volume:
