content = open('mpp_frontend/package.json','r',encoding='utf-8').read()
content = content.replace('"start": "react-scripts start"', '"start": "react-app-rewired start"')
content = content.replace('"build": "react-scripts build"', '"build": "react-app-rewired build"')
content = content.replace('"test": "react-scripts test"', '"test": "react-app-rewired test"')
open('mpp_frontend/package.json','w',encoding='utf-8').write(content)
print('Done')
