# Generated by Django 4.2.20 on 2025-03-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
