# Generated by Django 4.2.20 on 2025-03-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
