# Generated by Django 4.2.20 on 2025-03-21 19:26

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.upload_to_revision),
        ),
    ]
