# Generated by Django 4.2.20 on 2025-03-21 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='revision',
        ),
        migrations.CreateModel(
            name='FileRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(default=1)),
                ('file_path', models.CharField(max_length=1024)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='files.file')),
            ],
        ),
    ]
