# Generated by Django 4.2.1 on 2025-04-05 08:59

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_remove_file_revision_filerevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerevision',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.upload_to_revision),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='filerevision',
            name='file_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
