# Generated by Django 4.2.1 on 2025-06-02 12:13

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_product_stage_file_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filerevision',
            options={'ordering': ['-revision_number']},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='file',
            name='current_revision',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='file',
            name='is_child_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='parent_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_files', to='files.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='parent_revision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(default='In-Work', max_length=50),
        ),
        migrations.AddField(
            model_name='filerevision',
            name='change_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='filerevision',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='filerevision',
            name='status',
            field=models.CharField(default='In-Work', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='filerevision',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filerevision',
            name='revision_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filerevision',
            name='uploaded_file',
            field=models.FileField(default='', upload_to=files.models.upload_to_revision),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AlterField(
            model_name='stage',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('workflow', 'Workflow'), ('approval', 'Approval'), ('review', 'Review')], default='workflow', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='filerevision',
            unique_together={('file', 'revision_number')},
        ),
    ]
