# Generated by Django 4.2.1 on 2025-06-05 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0009_alter_filerevision_revision_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order', 'stage_number']},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='upload_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='filerevision',
            old_name='upload_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='label',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_child_file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='parent_revision',
        ),
        migrations.RemoveField(
            model_name='file',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='filerevision',
            name='change_description',
        ),
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word Document'), ('docx', 'Word Document (DOCX)'), ('xls', 'Excel Spreadsheet'), ('xlsx', 'Excel Spreadsheet (XLSX)'), ('ppt', 'PowerPoint'), ('pptx', 'PowerPoint (PPTX)'), ('txt', 'Text File'), ('csv', 'CSV File'), ('jpg', 'JPEG Image'), ('jpeg', 'JPEG Image'), ('png', 'PNG Image'), ('gif', 'GIF Image'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='filerevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filerevision',
            name='description',
            field=models.TextField(blank=True, help_text='Description of changes in this revision', null=True),
        ),
        migrations.AddField(
            model_name='filerevision',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for this file', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity for this file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('in_work', 'In Work'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('final', 'Final')], default='in_work', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.upload_to_file),
        ),
        migrations.AlterField(
            model_name='filerevision',
            name='revision_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filerevision',
            name='status',
            field=models.CharField(choices=[('in_work', 'In Work'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('final', 'Final')], default='in_work', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('workflow', 'Workflow'), ('approval', 'Approval'), ('review', 'Review'), ('development', 'Development'), ('testing', 'Testing'), ('production', 'Production')], default='workflow', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('product', 'name'), ('product', 'stage_number')},
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('iteration_number', models.IntegerField()),
                ('type', models.CharField(choices=[('design', 'Design'), ('prototype', 'Prototype'), ('testing', 'Testing'), ('refinement', 'Refinement'), ('final', 'Final')], default='design', max_length=20)),
                ('color', models.CharField(default='#28a745', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='files.product')),
            ],
            options={
                'ordering': ['order', 'iteration_number'],
                'unique_together': {('product', 'iteration_number'), ('product', 'name')},
            },
        ),
    ]
