# Generated by Django 4.2.1 on 2025-09-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_file_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word Document'), ('docx', 'Word Document (DOCX)'), ('txt', 'Text File'), ('xls', 'Excel Spreadsheet'), ('xlsx', 'Excel Spreadsheet (XLSX)'), ('csv', 'CSV File'), ('ppt', 'PowerPoint'), ('pptx', 'PowerPoint (PPTX)'), ('jpg', 'JPEG Image'), ('jpeg', 'JPEG Image'), ('png', 'PNG Image'), ('gif', 'GIF Image'), ('bmp', 'BMP Image'), ('svg', 'SVG Image'), ('tiff', 'TIFF Image'), ('c', 'C Source Code'), ('cpp', 'C++ Source Code'), ('cxx', 'C++ Source Code'), ('cc', 'C++ Source Code'), ('h', 'C/C++ Header File'), ('hpp', 'C++ Header File'), ('py', 'Python Script'), ('js', 'JavaScript'), ('ts', 'TypeScript'), ('java', 'Java Source Code'), ('cs', 'C# Source Code'), ('php', 'PHP Script'), ('rb', 'Ruby Script'), ('go', 'Go Source Code'), ('rs', 'Rust Source Code'), ('swift', 'Swift Source Code'), ('kt', 'Kotlin Source Code'), ('scala', 'Scala Source Code'), ('pl', 'Perl Script'), ('sh', 'Shell Script'), ('bat', 'Batch File'), ('ps1', 'PowerShell Script'), ('ino', 'Arduino Sketch'), ('pde', 'Processing/Arduino'), ('uf2', 'UF2 Firmware'), ('hex', 'Intel HEX File'), ('bin', 'Binary File'), ('elf', 'ELF Executable'), ('mpy', 'MicroPython Bytecode'), ('stl', 'STL 3D Model'), ('stp', 'STEP 3D Model'), ('step', 'STEP 3D Model'), ('iges', 'IGES 3D Model'), ('igs', 'IGES 3D Model'), ('obj', 'OBJ 3D Model'), ('3mf', '3MF 3D Model'), ('ply', 'PLY 3D Model'), ('fbx', 'FBX 3D Model'), ('dae', 'COLLADA 3D Model'), ('blend', 'Blender File'), ('max', '3ds Max File'), ('ma', 'Maya ASCII File'), ('mb', 'Maya Binary File'), ('dwg', 'AutoCAD Drawing'), ('dxf', 'DXF Drawing'), ('dwf', 'Design Web Format'), ('ipt', 'Inventor Part'), ('iam', 'Inventor Assembly'), ('idw', 'Inventor Drawing'), ('prt', 'SolidWorks/NX Part'), ('asm', 'SolidWorks Assembly'), ('sldprt', 'SolidWorks Part'), ('sldasm', 'SolidWorks Assembly'), ('slddrw', 'SolidWorks Drawing'), ('kicad_pro', 'KiCad Project'), ('kicad_sch', 'KiCad Schematic'), ('kicad_pcb', 'KiCad PCB'), ('lib', 'KiCad Symbol Library'), ('dcm', 'KiCad Component Documentation'), ('pretty', 'KiCad Footprint Library'), ('kicad_mod', 'KiCad Footprint'), ('net', 'KiCad Netlist'), ('cmp', 'KiCad Component List'), ('brd', 'Eagle Board'), ('sch', 'Eagle/Generic Schematic'), ('lbr', 'Eagle Library'), ('gerber', 'Gerber File'), ('gbr', 'Gerber File'), ('drl', 'Drill File'), ('nc', 'NC Drill File'), ('gcode', 'G-Code'), ('zip', 'ZIP Archive'), ('rar', 'RAR Archive'), ('7z', '7-Zip Archive'), ('tar', 'TAR Archive'), ('gz', 'GZIP Archive'), ('json', 'JSON Data'), ('xml', 'XML Data'), ('yaml', 'YAML Data'), ('yml', 'YAML Data'), ('toml', 'TOML Data'), ('ini', 'INI Configuration'), ('cfg', 'Configuration File'), ('conf', 'Configuration File'), ('md', 'Markdown'), ('rst', 'reStructuredText'), ('log', 'Log File'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
