# Generated by Django 4.2.1 on 2026-07-22 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0012_folder_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='folder',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
