# Generated by Django 4.2.1 on 2026-07-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_backfill_folder_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('mechanical', 'Mechanical'), ('misc', 'Misc')], default='misc', help_text='BOM category (electronics/mechanical/misc)', max_length=20),
        ),
    ]
