# Generated by Django 4.2.1 on 2026-07-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_backfill_file_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('PRD', 'Product Requirement'), ('ARCH', 'Architecture'), ('RISK', 'Risk / FMEA'), ('SRS', 'Software/System Requirement Spec'), ('VERIF', 'Verification'), ('VAL', 'Validation')], max_length=8)),
                ('tag_id', models.CharField(help_text='ID as written in the doc, e.g. R001 / REQ-01', max_length=64)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('source_line', models.PositiveIntegerField(default=0)),
                ('snippet', models.TextField(blank=True)),
                ('test_status', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=4, null=True)),
                ('subsystem', models.CharField(blank=True, max_length=120, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_nodes', to='files.product')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_nodes', to='files.file')),
                ('source_iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_nodes', to='files.iteration')),
            ],
            options={
                'ordering': ['node_type', 'tag_id'],
                'unique_together': {('product', 'source_iteration', 'node_type', 'tag_id')},
            },
        ),
        migrations.CreateModel(
            name='TraceEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tag_id', models.CharField(max_length=64)),
                ('child_tag_id', models.CharField(max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_edges', to='files.product')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_edges', to='files.file')),
            ],
            options={
                'ordering': ['parent_tag_id', 'child_tag_id'],
                'indexes': [models.Index(fields=['product', 'parent_tag_id'], name='files_trace_product_303dfd_idx'), models.Index(fields=['product', 'child_tag_id'], name='files_trace_product_cc5de4_idx')],
            },
        ),
    ]
