# Generated by Django 4.2.1 on 2026-08-14 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0018_tracematrixpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTraceEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tag_id', models.CharField(max_length=64)),
                ('child_tag_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_trace_edges', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_trace_edges', to='files.product')),
            ],
            options={
                'ordering': ['parent_tag_id', 'child_tag_id'],
                'indexes': [models.Index(fields=['product', 'parent_tag_id'], name='files_manua_product_a32823_idx'), models.Index(fields=['product', 'child_tag_id'], name='files_manua_product_40ff7b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='manualtraceedge',
            constraint=models.UniqueConstraint(fields=('product', 'parent_tag_id', 'child_tag_id'), name='uniq_manual_trace_edge'),
        ),
    ]
